# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2024, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# Takanori Suzuki <takanori@takanory.net>, 2021
# tomo, 2021
# 石井明久, 2024
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.13\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-10-11 14:17+0000\n"
"PO-Revision-Date: 2021-06-28 00:55+0000\n"
"Last-Translator: 石井明久, 2024\n"
"Language-Team: Japanese (https://app.transifex.com/python-doc/teams/5390/"
"ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../../library/audit_events.rst:6
msgid "Audit events table"
msgstr "監査イベント表"

#: ../../library/audit_events.rst:8
msgid ""
"This table contains all events raised by :func:`sys.audit` or :c:func:"
"`PySys_Audit` calls throughout the CPython runtime and the standard "
"library.  These calls were added in 3.8 or later (see :pep:`578`)."
msgstr ""
"この表は、 CPython ランタイムと標準ライブラリ全体で :func:`sys.audit` また"
"は :c:func:`PySys_Audit` の呼び出しによって送出されるすべてのイベントを含んで"
"います。これらの呼び出しは、 3.8 以降に追加されました (:pep:`578` を参照) 。"

#: ../../library/audit_events.rst:12
msgid ""
"See :func:`sys.addaudithook` and :c:func:`PySys_AddAuditHook` for "
"information on handling these events."
msgstr ""
"これらのイベントの処理についての情報は :func:`sys.addaudithook` と :c:func:"
"`PySys_AddAuditHook` を参照してください。"

#: ../../library/audit_events.rst:17
msgid ""
"This table is generated from the CPython documentation, and may not "
"represent events raised by other implementations. See your runtime specific "
"documentation for actual events raised."
msgstr ""
"この表は CPython ドキュメントから生成されており、他の実装により送出されるイベ"
"ントを表示していない可能性があります。実際に送出されるイベントは、ランタイム"
"固有のドキュメントを参照してください。"

#: ../../library/audit_events.rst:23
msgid ""
"The following events are raised internally and do not correspond to any "
"public API of CPython:"
msgstr "以下のイベントは内部で送出され、 CPython の公開 API に対応しません。"

#: ../../library/audit_events.rst:27
msgid "Audit event"
msgstr "監査イベント"

#: ../../library/audit_events.rst:27
msgid "Arguments"
msgstr "引数"

#: ../../library/audit_events.rst:29
msgid "_winapi.CreateFile"
msgstr "_winapi.CreateFile"

#: ../../library/audit_events.rst:29
msgid ""
"``file_name``, ``desired_access``, ``share_mode``, ``creation_disposition``, "
"``flags_and_attributes``"
msgstr ""
"``file_name``, ``desired_access``, ``share_mode``, ``creation_disposition``, "
"``flags_and_attributes``"

#: ../../library/audit_events.rst:33
msgid "_winapi.CreateJunction"
msgstr "_winapi.CreateJunction"

#: ../../library/audit_events.rst:33
msgid "``src_path``, ``dst_path``"
msgstr "``src_path``, ``dst_path``"

#: ../../library/audit_events.rst:35
msgid "_winapi.CreateNamedPipe"
msgstr "_winapi.CreateNamedPipe"

#: ../../library/audit_events.rst:35
msgid "``name``, ``open_mode``, ``pipe_mode``"
msgstr "``name``, ``open_mode``, ``pipe_mode``"

#: ../../library/audit_events.rst:37
msgid "_winapi.CreatePipe"
msgstr "_winapi.CreatePipe"

#: ../../library/audit_events.rst:39
msgid "_winapi.CreateProcess"
msgstr "_winapi.CreateProcess"

#: ../../library/audit_events.rst:39
msgid "``application_name``, ``command_line``, ``current_directory``"
msgstr "``application_name``, ``command_line``, ``current_directory``"

#: ../../library/audit_events.rst:42
msgid "_winapi.OpenProcess"
msgstr "_winapi.OpenProcess"

#: ../../library/audit_events.rst:42
msgid "``process_id``, ``desired_access``"
msgstr "``process_id``, ``desired_access``"

#: ../../library/audit_events.rst:44
msgid "_winapi.TerminateProcess"
msgstr "_winapi.TerminateProcess"

#: ../../library/audit_events.rst:44
msgid "``handle``, ``exit_code``"
msgstr "``handle``, ``exit_code``"

#: ../../library/audit_events.rst:46
msgid "ctypes.PyObj_FromPtr"
msgstr "ctypes.PyObj_FromPtr"

#: ../../library/audit_events.rst:46
msgid "``obj``"
msgstr "``obj``"

#: ../../library/audit_events.rst:3
msgid "audit events"
msgstr "監査イベント"
